openapi: 3.0.2
info:
  title: PraiseHub
  description: 褒めるアプリAPI
  version: 1.0.0
servers:
  - url: http://localhost:8002/api
    description: ローカルのAPIサーバー
tags:
  - name: User
    description: ユーザーに関するAPI
